# Generated by Django 4.0.3 on 2023-01-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
