# Generated by Django 4.0.3 on 2023-01-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_writer_display_name_alter_section_sub_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='BlogSection',
        ),
    ]
