# Generated by Django 4.0.3 on 2023-01-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_section_blogsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogSection',
            new_name='BlogPostSection',
        ),
    ]
