# Generated by Django 4.1.5 on 2023-01-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffuser_profile_picture_and_more'),
        ('app', '0006_blog_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.ImageField(upload_to='blog_cover_photos'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffuser'),
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
