# Generated by Django 4.1.5 on 2023-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.ImageField(upload_to='blog_cover_photos'),
        ),
    ]
