# Generated by Django 4.1.5 on 2023-01-12 08:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_cover_photo_alter_blogpost_post_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
