# Generated by Django 4.1.5 on 2023-01-12 10:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blogpostsection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsection',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
