# Generated by Django 4.1.5 on 2023-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='designation',
            field=models.CharField(choices=[('admin', 'Admin'), ('writer', 'Writer')], default='writer', max_length=200),
        ),
    ]
